swipe:
  3:
    left:
      # command: 'fusuma-sendkey LEFTALT+LEFTMETA+RIGHT'
      command: 'xdotool key alt+super+Right'
    right:
      # command: 'fusuma-sendkey LEFTALT+LEFTMETA+LEFT'
      command: 'xdotool key alt+super+Left'
