swipe:
  3:
    down:
      # command: 'fusuma-sendkey LEFTALT+LEFTMETA+LEFT'
      command: 'xdotool key alt+super+Left'
    up:
      # command: 'fusuma-sendkey LEFTALT+LEFTMETA+RIGHT'
      command: 'xdotool key alt+super+Right'
    left:
      # command: 'funuma-sendkey LEFTALT+J'
      command: 'xdotool key alt+j'
    right:
      # command: 'fusuma-sendkey LEFTALT+K'
      command: 'xdotool key alt+k'
